### ISSUE TITLE
Unable to set up reversing API

### ISSUE THREAD

**Issue by Connor-woodahl** [UbiquityRobotics/move_basic#109]
When trying to run the following on our AGV, 

cd /home/ubuntu/catkin_ws/src/move_basic
git pull
git checkout reversing
cd /home/ubuntu/catkin_ws/src/ezmap
git pull
git checkout v1.1.4-QCM-reversing

I ran into an error when trying to perform the second pull: 
remote: Repository not found.
fatal: repository 'https://github.com/UbiquityRobotics/ezmap.git/' not found

**Comment by anfederman** [comment]
Ez map is a private repository, you need to be given permission to see or
download.

**Comment by anfederman** [comment]
Dave Crawley  ***@***.***) Is an owner, and can grant
permission to ezmap. You will need to tell us your github account name.

**Comment by Connor-woodahl** [comment]
Github account: Connor-woodahl

**Comment by MoffKalast** [comment]
Seems like your initial email invite has expired, check your inbox for another one.

**Comment by Connor-woodahl** [comment]
Thank you!
