### ISSUE TITLE
Going backwards doesn't work

### ISSUE THREAD

**Issue by jim-v** [UbiquityRobotics/move_basic#24]
@jrlandau reported that goals behind don't work.

Question: should it handle this as a special case and actually move backwards, or do the arctan planner thing and rotate to face the goal and drive towards it?  If it moves backwards, then a front-facing LIDAR does not provide obstacle detection.

Definition of done:
Backwards goals result in behavior that considered reasonable by consensus.

**Comment by jrlandau** [comment]
turning round takes quite some space, but moving backwards takes less, so
it may be useful to get out of a tight spot.

**Comment by rohbotics** [comment]
Maybe it makes sense to go backward for short goals (<0.5 m) and do the atan2 method for backward goals beyond that distance?

**Comment by rohbotics** [comment]
Decision:

If within a threshold backward and in angular threshold, then arctan backward.

Otherwise do the 'current behavior' sans bugs.
