### ISSUE TITLE
Laser frame hardcoded in move_basic

### ISSUE THREAD

**Issue by anfederman** [UbiquityRobotics/move_basic#40]
On my bot vac which is getting LDS Scan data, my obstacle distance is fxed at 9.9

getting this warning:

[ WARN] [1529711837.494609404]: "laser" passed to lookupTransform argument source_frame does not exist. 

Additional Data:

$ rostopic info /scan
Type: sensor_msgs/LaserScan

Publishers: 
 * /neato (http://ubiquityrobot.local:43879/)

Subscribers: 
 * /move_basic (http://ubiquityrobot.local:40399/)

alan@anfrosbase:~/catkin_ws/src/magni_robot/magni_nav/launch$ cd
alan@anfrosbase:~$ rosmsg show sensor_msgs/LaserScan
std_msgs/Header header
  uint32 seq
  time stamp
  string frame_id
float32 angle_min
float32 angle_max
float32 angle_increment
float32 time_increment
float32 scan_time
float32 range_min
float32 range_max
float32[] ranges
float32[] intensities

alan@anfrosbase:~$ rostopic info /obstacle_distance 
Type: std_msgs/Float32

Publishers: 
 * /move_basic (http://ubiquityrobot.local:40399/)

Subscribers: None

---
data: 9.89999961853
---
My guess is I am missing a transform from base_link  or base_laser_link, but I don't know.

**Comment by rohbotics** [comment]
In move_basic the "laser" frame is hardcoded instead of looked up via the message.
