### ISSUE TITLE
Smoothly operate between multiple goals

### ISSUE THREAD

**Issue by rohbotics** [UbiquityRobotics/move_basic#53]
Design Spec (gDoc) https://docs.google.com/document/d/1VMVLXGuo9FLRNtYYDwZhG0O-8cJYbZzX8QA-8RhGGFY/edit?usp=sharing

**Comment by MoffKalast** [comment]
[Current design spec.](https://slack-files.com/files-pri-safe/T04BZFRLG-F012W3G1RDY/multiple_goals_in_move_basic_v2.pdf?c=1590092159-a6f24a310c009ba1)

**Comment by dorkamotorka** [comment]
Done in the breadcrumb repository. In near future we should decide whether we will merge it into move_basic or create a separate package. Closing
