### ISSUE TITLE
distRemaining is constant

### ISSUE THREAD

**Issue by THOSE-EYES** [UbiquityRobotics/move_basic#63]
The problem is that distRemaining is always constant due to being assigned using the "linear" variable. The solution is to change line 738 
`double distRemaining = sqrt(linear.x() * linear.x() + linear.y() * linear.y());`
to 
`double distRemaining = sqrt(remaining.x() * remaining.x() + remaining.y() * remaining.y());`

The solution is tested and works fully.

**Comment by dorkamotorka** [comment]
Thank you for the request. Changes have been applied.
