### ISSUE TITLE
max_lateral_rotation and max_angular_velocity parameters not clear and undocumented

### ISSUE THREAD

**Issue by JanezCim** [UbiquityRobotics/move_basic#74]
Found out that parameter `max_angular_velocity` is meant for maximum angular velocity, while robot is **turning on the spot**, while the parameter `max_lateral_rotation` controls the maximum angular velocity while **driving towards goal**. This answers this issue but maybe the names of the parameters are a bit unintuitive? The [ROS wiki page](http://wiki.ros.org/move_basic) also doesn't even mention param `max_lateral_rotation`

**suggestion1:** new names: max_turning_velocity, max_lateral_velocity
**suggestion2:** we set the max_lateral_velocity = max_turning_velocity as default with 
`nh.param<double>("max_lateral_velocity", maxLateralVelocity, maxTurningVelocity);`
as this would still lave the user the control over both, but default parameters would be a bit easier to understand.

If we don't rename parameters, we should at least update documentation on ROS wiki page (we have to do that anyway).

**Comment by dorkamotorka** [comment]
Suggestion1 was implemented in #76
