### ISSUE TITLE
Add dynamic reconfigure to move basic

### ISSUE THREAD

**Issue by JanezCim** [UbiquityRobotics/move_basic#75]
It would be beneficial to add params of move basic to dynamic reconfigure as it would enable faster debugging and optimising

**Comment by JanezCim** [comment]
This is being addressed in branch `feature-dynamic_reconfigure`

**Comment by dorkamotorka** [comment]
This is implemented #76 and will close this issue when merged.

**Comment by JanezCim** [comment]
This was done
