### ISSUE TITLE
move_basic Features

### ISSUE THREAD

**Issue by dorkamotorka** [UbiquityRobotics/move_basic#84]
This Issue names the features included in `nav-features` branch that will be merged into `kinetic-devel` once all the relevant people agree. 

Last stable commit was `7148b24c7c5a436e56fcefe9fc344dfd12be1edb` on branch `nav-features`. If any of the features break your code, please refer to this commit and report your problem in this issue.
Changes applied from last stable commit are:
- **Removed velocity gains**(`latGain`, `linGain`, `rotGain`) 
             **REASON**: Unintuitive for the end user
             **COUNTER WEIGHT**: Increased values for both minLinearVelocity & minTurningVelocity so that robot is not moving to 
                                                      slow + retuned PID parameters for lateral correction when moving linear
- **Added stopCallback**
             **REASON**: Enables us to stop and resume the last navigation task through topic (no need to cancel all goals and 
                                    resend them) - This should further changed to ROS Service
- **Oscillations**
             **REASON**: When turning on spot robot can oscillate around the final orientation no more than 3 times, this enables us 
                                    to miss a final orientation but give a second try(is already present in kinetic-devel)
- **Removed `velThreshold` parameter**
             **REASON**: It doesn't give any significant change - linearTolerance parameter for checking if we are close enough to a 
                                    goal is good enough for now
- **False final orientation quaternion**
             **REASON**: Proposed for projects ease handling
- **Abort moving away from goal**
             **REASON**: Abort before any unpredicted behaviour
             **WORKING PRINCIPLE**: If robot moves away from goal(cosine of angleRemaining) for more than runawayTimeout 
                                                          duration, we mark that as moving away from goal and abort it
- **Added `minLinearVelocity`, `minAngularVelocity`**
             **REASON**: This way robot IRL is always able to perform a maneuver and is not stuck by its physical constraints
- **Renamed parameters**
             **REASON**: To be more intuitive for the end-user

**Comment by JanezCim** [comment]
I think the HEAD on nav-features is now sufficiently bettern then this last stable so we can close this
